server:
  tomcat:
    threads:
      max: 20
  port: 8080

spring:
  main:
    banner-mode: off
  application:
    name: self-monitor
  config:
    import: optional:file:/config/application.yaml

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pp}
    username: ${DB_USER:pp}
    password: ${DB_PASS:password}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/main.yaml

clients:
  api:
    key: ${CLIENTS_API_KEY:KEY}

import:
  size:
    max: 50

springdoc:
  swagger-ui:
    urls:
      - name: self-monitor
        url: /oas/self-monitor.yaml

logging:
  level:
    root: info
