apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: praise-regret-ingress
  namespace: api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pp.rabko.online
      secretName: pp-rabko-online-tls
  rules:
    - host: pp.rabko.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: praise-regret-log
                port:
                  number: 80