apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "self-monitor.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
{{ .Files.Get "application.yaml" | indent 4 }}
