apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "self-monitor.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "self-monitor.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "self-monitor.name" . }}
    spec:
      containers:
        - name: {{ include "self-monitor.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.jvmOpts }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "self-monitor.fullname" . }}-config
