apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-monitor.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "self-monitor.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
